module.exports = {
  CORE_SERVICE_PORT: process.env.PORT,
  NODE_ENV: process.env.NODE_ENV,
  SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
  SPOTIFY_REDIRECT_URI: process.env.SPOTIFY_REDIRECT_URI,
  MUSIC_DL_PRIMARY_DB: process.env.MUSIC_DL_PRIMARY_DB,
  SPOTIFY_ACCESS_TOKEN_URL: process.env.SPOTIFY_ACCESS_TOKEN_URL,
  TMP_DIRECTORY_PATH: process.env.TMP_DIRECTORY_PATH,
  SPOTIFY_ACCESS_TOKEN_FILE: process.env.SPOTIFY_ACCESS_TOKEN_FILE,
  ACCESS_TOKEN_REFRESH_INTERVAL: process.env.ACCESS_TOKEN_REFRESH_INTERVAL,
  MAX_RETRY: process.env.MAX_RETRY,
};
