module.exports = {
  apps: [
    {
      name: 'm-dl-core',
      cwd: '',
      script: 'npm',
      args: 'start',
      env: {
        PORT: '',
        NODE_ENV: '',
        SPOTIFY_CLIENT_ID: '',
        SPOTIFY_CLIENT_SECRET: '',
        SPOTIFY_REDIRECT_URI: '',
        MUSIC_DL_PRIMARY_DB: '',
        SPOTIFY_ACCESS_TOKEN_URL: '',
        TMP_DIRECTORY_PATH: '',
        SPOTIFY_ACCESS_TOKEN_FILE: '',
        ACCESS_TOKEN_REFRESH_INTERVAL: '',
        MAX_RETRY: '',
        SPOTIFY_API_TIMEOUT: '',
        MAX_API_TIMEOUT: '',
        MUSIC_MAX_DURATION: '',
        YT_MP4_CONVERTER_URL: '',
        YT_GOOGLE_CDN_TOKEN: '',
        YT_MP4_QUALITY: '',
        DOWNLOAD_PATH_MP4: '',
        DOWNLOAD_PATH_MP3: '',
        MUSIC_DL_STORAGE_ACCESS_TOKEN: '',
        MUSIC_DL_STORAGE_USER: '',
        MUSIC_DL_STORAGE_USER_EMAIL: '',
        MUSIC_DL_BUCKET_NAME: '',
        MUSIC_DL_STORAGE_HOST: '',
        MUSIC_DL_CDN_HOST: '',
      },
    },
  ],
};
